# PostgreSQL. Versions 8.2 and up are supported.
# Use 'createuser -s postgres' to create a general purpose db (super)user.

development: &default
  adapter: sqlite3
  database: db/spellpad_development.sqlite3
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: spellpad_test
  min_messages: warning
